# Generated by Django 3.0.7 on 2020-06-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='details/static/details/assets')),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('date ended', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
