# Generated by Django 3.0.7 on 2020-06-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Project',
        ),
    ]
